version: "3.1"
services:
  recipes-api:
    container_name: recipes-api
    depends_on:
      - recipes-db
      - recipes-cache
    build:
      context: .
      dockerfile: ./Dockerfile-backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/:/usr/src/backend
      - /usr/src/backend/node_modules
      - /usr/src/backend/static
    restart: unless-stopped
    links:
      - recipes-db
      - recipes-cache
  recipes-db:
    container_name: recipes-db
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./backend/recipes-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
  recipes-cache:
    container_name: recipes-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - recipes-cache:/data
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  redis-commander:
    depends_on:
      - recipes-cache
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=recipes-cache
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
    ports:
      - "8081:8081"
  recipes-web:
    container_name: recipes-web
    depends_on:
      - recipes-api
    volumes:
      - ./frontend/:/usr/src/frontend
      - /usr/src/frontend/node_modules
      - /usr/src/frontend/.next
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    build:
      context: .
      dockerfile: ./Dockerfile-frontend
volumes:
  recipes-db:
    driver: local
  recipes-cache:
    driver: local
  recipes-web:
    driver: local
  recipes-apo:
    driver: local

networks:
  app-network:
    driver: bridge
