version: '3.1'
services:
  recipes-api:
    container_name: recipes-api
    depends_on:
      - recipes-db
      - recipes-cache
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./:/src
    env_file:
      - .env
    restart: unless-stopped
    links:
      - recipes-db
      - recipes-cache
  recipes-db:
    container_name: recipes-db
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./recipes-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
  recipes-cache:
    container_name: recipes-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - recipes-cache:/data
volumes:
  recipes-db:
    driver: local
  recipes-cache:
    driver: local
